### ISSUE TITLE
Problemas al abrir el proyecto

### ISSUE THREAD

**Issue by cbarreraa** [OctetoStudios/c2-helloworld#12]
![image](https://cloud.githubusercontent.com/assets/23122294/19815391/ff210910-9d18-11e6-9f50-9a2fb1c47766.png)
El problema sucede luego del comit de @jmarambio  https://github.com/OctetoStudios/c2-helloworld/commit/06a7c7f91b93a3caaa9c7727dc8f1b6cbbafdacf

**Comment by gogaete** [comment]
Se hizo mal el merge.
Se eliminó incorrectamente el cierre del tag object-type
