### ISSUE TITLE
Create & add background

### ISSUE THREAD

**Issue by gogaete** [OctetoStudios/c2-helloworld#5]
Create two different backgrounds & add them to the two game layouts.
Layer: background layer.

Some references:
![bg01](https://cloud.githubusercontent.com/assets/22986131/19792158/33020750-9c9e-11e6-8b3e-c89759ba7cce.jpg)
![bg02](https://cloud.githubusercontent.com/assets/22986131/19792159/3483431e-9c9e-11e6-8be8-c3e2abc890d6.jpg)

**Comment by jmarambio** [comment]
Completado.
